#+title: A maior força militar que a humanidade já viu foi colocada de joelhos
#+setupfile: opiniao-capa.org

#+LATEX_HEADER: \setlength{\parskip}{1em}
#+LATEX_HEADER: \pagestyle{empty}

#+begin_export latex
\thispagestyle{empty}
\newgeometry{margin=0cm}
\begin{center}
  \includegraphics[width=.95\paperwidth,height=.95\paperheight]{eua-joelhos-capa.png}
\end{center}
\restoregeometry
\clearpage
\begin{multicols}{2}
#+end_export

Hoje, 7 de abril de 2026, a República Islâmica do Irã força o governo norte-americano a um cessar-fogo de duas semanas e a considerar os 10 pontos apresentados para acordo.

A máquina de matar norte-americana parecia impossível de parar. Com um gasto militar anual de US$ 919,2 bilhões, correspondendo a aproximadamente 37% dos gastos militares globais, é o maior gasto militar do mundo, chegando a superar a soma dos gastos dos demais nove países do ranking. Não se trata apenas de uma força militar muito maior do que a dos demais países de hoje em dia; é a maior força militar que a humanidade já viu.

Um poder militar gigantesco combinado com a falta de qualquer escrúpulo. Atingindo escolas primárias, matando centenas de crianças, líderes políticos e religiosos, atacando universidades, hospitais e equipes de resgate desde os primeiros dias de guerra, colocam em prática uma estratégia deliberada de manter o terror entre a população iraniana.

Isso tudo faz dessa vitória, mesmo que parcial, uma façanha impressionante. Observando apenas os últimos eventos, desde sexta-feira (3), o Irã abateu 4 aeronaves e 9 helicópteros. Dentre eles, o abatimento de um F-15E, algo que não ocorria desde a Guerra do Golfo em 1991.

Além da destruição dos radares das doze bases norte-americanas nos países do Golfo, que causam um prejuízo aos EUA que ultrapassa US$ 4 bilhões. Uma das demonstrações mais impressionantes de precisão foi o ataque realizado contra a Base Aérea Príncipe Sultan, na Arábia Saudita, a mais de 850 km de Teerã, atingindo o Boeing E-3 Sentry (AWACS) dos Estados Unidos, avaliado em centenas de milhões de dólares.

As bases norte-americanas que se estendem por todo o Golfo Pérsico e cercam o território iraniano ou serão retiradas por desejo do Irã ou permanecerão e se tornarão alvos futuros muito vulneráveis. Elas perderam completamente a função; os radares demorarão anos para serem reconstruídos e a capacidade dos mísseis iranianos parece estar em pleno funcionamento.

O fechamento do Estreito de Ormuz, realizado em grande parte devido ao temor das seguradoras marítimas, levou o preço do petróleo a subir de US$ 72,48 por barril, atingindo um pico de US$ 119,50 (9 de março), o maior valor desde 2022. Previsões indicavam impactos de curto prazo nos preços dos combustíveis e, a médio prazo, um impacto catastrófico nos setores diretamente derivados do petróleo, como os plásticos, e do gás, como os fertilizantes. A perspectiva de uma recessão global estava presente e ainda está associada à continuidade da guerra.

Como efeito indireto, mas também incluído entre as conquistas iranianas, a guerra contra o Irã era extremamente impopular. Com um racha significativo na base trumpista, à medida que a guerra avançava e a situação se assemelhava a uma areia movediça — quanto mais o regime de Washington se movia, mais sua popularidade despencava, chegando a níveis muito baixos.

Se a guerra parar agora, o movimento trumpista, com seu /slogan/ “A América em Primeiro Lugar” (/America First/), pode ser considerado enterrado. Para aqueles em sua base que não queriam a guerra, esse conflito foi visto como desnecessário e como um estelionato eleitoral; para aqueles que advogavam pela guerra, principalmente os mais alinhados ao partido republicano tradicional (os chamados /neocons/), será difícil encobrir o fracasso.

O Trump que, na eleição, venceu o Colégio Eleitoral, a maioria dos votos, o Senado e a Câmara, vê, com essa guerra, uma rápida corrosão de qualquer movimento popular.

Em seis semanas os iranianos colocaram os governos norte-americano e israelense em um beco sem saída, fizeram com que os demais países imperialistas repensassem suas posições e recuassem frente a encalacrada. Seria um exagero afirmar que essa é uma vitória definitiva e que a ditadura a que o imperialismo submete o mundo está em colapso; contudo, dada a disparidade de armas e o tamanho da tarefa a ser alcançada, creio que seja importante comemorar cada vitória, e, neste pequeno capítulo da história, a vitória não está nas mãos do imperialismo.

A República Islâmica do Irã deixa uma lição importante para todos os povos oprimidos do mundo.

Uma lição importante, como a da frase clássica do filme O Predador (1987), dita pelo personagem Dutch (Arnold Schwarzenegger): \\
*“Se sangra, podemos matá-lo”*.
\hspace{1em}\pgfornament[height=.5em]{2}

\vspace{1em}
\footnotesize
Texto original em:\\
=https://www.rodrigues-am.xyz/posts/eua-joelhos/=

#+begin_export latex
\end{multicols}
#+end_export
