#+setupfile: opiniao-estilo.org
#+title: As mulheres iranianas não importam!
#+author: André Rodrigues
#+date: 6 de março de 2026
#+LATEX_HEADER: \setlength{\parskip}{.85em}

No dia 28 de fevereiro, durante as rodadas de negociação que aconteciam em Genebra, os Estados Unidos e Israel atacaram a República Islâmica do Irã. A agressão criminosa teve início com bombardeios em áreas civis em diversas partes do Irã, incluindo a capital Teerã. Os bombardeios norte-americanos a Minab atingiram uma escola primária feminina, deixando mais de 170 mortos — dados de 6 de março —, em sua grande maioria meninas estudantes da escola e professoras do ensino primário.

Durante anos, a imprensa imperialista e suas sucursais no Brasil empreenderam uma campanha ardilosa utilizando a questão da mulher iraniana como cobertura para as inúmeras tentativas de desestabilização do Irã. No final de 2025, após um ataque especulativo promovido pelos Estados Unidos que derrubou a moeda iraniana e com grupos armados pelas agências de inteligência israelenses (Mossad), norte-americanas (CIA) e britânicas (MI6), teve início um processo de desestabilização. A tentativa de revolução colorida, que deixou mais de três mil mortos entre detratores, apoiadores do governo e forças de segurança, foi frustrada pelo governo iraniano em poucas semanas.

Sob o comando de Donald Trump e Benjamin Netanyahu, as faces públicas do ataque ao Irã, cuja cobertura exaustivamente propagandeada sobre a libertação das mulheres iranianas simplesmente derreteu. É difícil imaginar a frase: "precisamos proteger e libertar as oprimidas mulheres iranianas" saindo da boca de Trump, sem que fique evidente a canalhice.

Por outro lado, a defesa da democracia na República Islâmica do Irã, a contracapa da propaganda imperialista norte-americana e europeia, também já está combalida, principalmente após os ataques à Venezuela, poucas semanas antes. O caso venezuelano mostrou que, mesmo para as mentes mais domesticadas pela propaganda — especialmente na esquerda —, a narrativa sobre a necessidade da democracia venezuelana evaporou já no primeiro pronunciamento do presidente americano. Do mesmo modo, a propaganda sobre as supostas drogas que saíam da Venezuela se mostrou patética.

Com o completo derretimento da propaganda imperialista e com o enorme volume de informações que circulam na internet e, particularmente, nas redes sociais, as motivações e justificativas tornam-se cruamente cristalinas. Como fica evidente pela posição da imprensa imperialista e pelo pronunciamento dos governos da União Europeia, a verdade é que as mulheres não importam; ou, colocada de modo rigoroso, as mulheres importam apenas quando podem ser usadas como propaganda e cobertura para os inúmeros crimes promovidos pelo imperialismo nos países oprimidos.

A verdade é que o imperialismo decide quais mulheres devem importar. As meninas assassinadas ou as mulheres iranianas que apoiam o governo do Irã contra a invasão imperialista de seu próprio país não podem ser consideradas. Essas mulheres não contam, apesar de serem milhões.

Tudo isso é bem ilustrado pelo editorial do /Estadão/ que, sem muitas voltas, joga toda a quinquilharia ideológica sobre a defesa da mulher e da democracia no lixo para apoiar o ataque ilegal ao Irã.

No título do editorial do jornal O Estado de S. Paulo, de 28 de fevereiro de 2026, lê-se: "Ninguém vai chorar pelo Irã". Mas cereja do bolo está no editorial do /Estadão/ que conclui citando diretamente Netanyahu:
#+begin_quote

/[...] A clareza moral impõe reconhecer que o Irã é um Estado pária e não pode ter uma bomba nuclear em hipótese alguma. Israel tem pleno direito de se defender de uma ameaça existencial inequívoca. “Chegou a hora de todas as partes do povo iraniano livrarem-se do jugo da tirania e promoverem um Irã livre e comprometido com a paz”, disse o premiê israelense, Benjamin Netanyahu. Sejam lá quais as motivações por trás da guerra, se esse for o seu resultado, será bom para o mundo inteiro./

#+end_quote
O editorial do Estadão está em sintonia com a declaração feita nos anos 1990 sobre a guerra econômica travada contra os iranianos.

Madeleine Albright, que foi embaixadora dos Estados Unidos nas Nações Unidas entre 1993 e 1997, supervisionando, entre outras coisas, as sanções econômicas ao Iraque e, posteriormente, ascendeu ao cargo de secretária de Estado do governo Clinton, entre 1997 e 2001. Ela foi a primeira mulher na história a exercer o cargo de secretária de Estado dos Estados Unidos; para um cargo não eleito, é difícil imaginar um maior exercício de poder no aparato imperialista. Algo que muitos hoje parecem estar convencidos de que deveria ser bradado como um avanço na luta das mulheres, um ponto alto da representatividade feminina.

Em 1996, em uma infame entrevista, Albright, mesmo depois de ter admitido alguns minutos antes, na mesma entrevista, que as sanções econômicas causaram efeitos catastróficos sobre a população pobre iraquiana, sem produzir os efeitos esperados sobre o governo de Saddam Hussein, foi questionada:

/Lesley Stahl:/ Ouvimos dizer que meio milhão de crianças morreram. Quero dizer, são mais crianças do que as que morreram em Hiroshima e, sabe, o preço vale a pena?

/Madeleine Albright:/ Acho que esta é uma escolha muito difícil, mas o preço -- *nós achamos que o preço vale a pena*. É uma questão moral, mas a questão moral é ainda maior: não devemos ao povo americano, aos militares americanos e aos outros países da região garantir que isso não seja uma ameaça?

A fala de Albright nos lembra que o imperialismo não se importa nem um pouco com as mulheres e meninas e está disposto a sacrificá-las sempre que lhe for conveniente. Aqueles que se deixam seduzir por qualquer propaganda moralista impulsionada pelo imperialismo dão as mãos a esse tipo de figura nefasta e também mancham as próprias mãos com o sangue das meninas que outrora acreditavam defender.
\hspace{1.2em}\pgfornament[height=0.8em]{1}

\vspace{20em}
Texto original em:\\
\scriptsize
=https://www.rodrigues-am.xyz/posts/ira-mulheres/=
