#+hugo_base_dir: ./
#+hugo_weight: auto
#+hugo_front_matter_key_replace: description>summary
#+author: André Rodrigues

* About
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_DATE: 2021-04-10
:EXPORT_FILE_NAME: about
:END:

#+begin_description
About me!
#+end_description

Hi!  My name is André Roodrigues.

I am an assistant professor at the Institute of Physics -- the University of São Paulo in Brazil. In the last decade, I have researched scientific concept formation, STEM education, educational data analysis with R, and cultural-historical psychology. This blog attempts to keep a consistent register of the journey as a researcher in the science education field.



/email:/ [[mailto:rodrigues.am@usp.br][rodrigues.am@usp.br]]

/twitter:/ [[https://twitter.com/andremrod][@andremrod]]


* Blogging :@blogging:
** DONE Hugo blog with Org and GitHub Actions                      :hugo:org:
:PROPERTIES:
:EXPORT_FILE_NAME: creating-hugo-blog-post
:EXPORT_DATE: 2021-02-05
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true
:END:

#+begin_description
In which I setup a working environment for writing a Hugo blog in Org with
automatic deployment using GitHub Actions.
#+end_description

*** Motivation
Like many dyed-in-the-wool Emacs users, I use [[https://orgmode.org][Org Mode]] for much of my writing. I
want a blog that I can deploy and write posts for in Org with minimum fuss.
Having heard good things about it, I want to give [[https://gohugo.io][Hugo]] a try. I also want to
have automatic deployment with [[https://github.com/features/actions][GitHub Actions]].



** Teste 1 :test:
:PROPERTIES:
:EXPORT_FILE_NAME: post-test
:EXPORT_DATE: 2021-02-05
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true
:END:
Promeiro post via ox-hugo. Alguns testes *são necessários*. Verificar as letras =teste=.

